Repository dig-eg-gaz/content, pull requests merged in 2018-02, with the labels that each got.

#639 Deliverable 3
  1906-10-08.xml
Labels: complete, deliverable3

#641 Monday Issue Pages 1-8
  1907-01-28.xml
Labels: complete, deliverable3

#644 Deliverables 1-3
  1907-04-08.xml
Labels: complete, deliverable3

#656 Deliverable 4
  1906-06-12.xml
Labels: complete, deliverable4

#653 Deliverable 4
  1907-05-21.xml
Labels: complete, deliverable4

#640 Deliverable 1 (1907-07-08)
  1907-07-08.xml
Labels: complete, deliverable1

#615 Deliverable 2
  1907-04-22.xml
  1907-04-23.xml
  1907-04-24.xml
Labels: deliverable4, deliverable5
