Repository dig-eg-gaz/content, pull requests merged in 2018-04, with the labels that each got.

#649 Deliverable 4-9
  1907-04-09.xml
  1907-04-10.xml
  1907-04-11.xml
  1907-04-12.xml
  1907-04-13.xml
  2018-03-05-Pregasen-md
Labels: deliverable4

#660 Deliverable 3
  1906-10-29.xml
Labels: complete, deliverable2, deliverable3

#635 1907-02-18
  1907-02-18.xml
  1907-02-19.xml
  1907-02-20.xml
  Blog Post Actual
  Blog Post Doc.docx
Labels: complete, deliverable2, deliverable3, deliverable4, deliverable5

#700 1907-06-27 Deliverable 5
  1907-06-27.xml
Labels: complete, deliverable7

#668 Deliverable 2
  1907-07-08.xml
  1907-07-09.xml
Labels: complete, deliverable4

#705 Add files via upload
  1905-07-21.xml
Labels: complete, deliverable8

#706 Deliverable 9
  1907-02-09.xml
Labels: complete, deliverable9

#677 p
  1907-03-18.xml
  1907-03-19.xml
  1907-03-21.xml
Labels: deliverable2, deliverable3, deliverable4
