Repository dig-eg-gaz/content, pull requests merged in 2018-03, with the labels that each got.

#662 1907-06-18.xml
  1907-06-18.xml
Labels: complete, deliverable4

#620 1906-03-05
  1906-03-05.xml
  1906-03-06.xml
  1906-03-07.xml
Labels: deliverable2

#665 Deliverable 5
  1907-05-22.xml
Labels: deliverable5

#617 Add files via upload
  1905-07-17.xml
  1905-07-18.xml
  1905-07-19.xml
Labels: deliverable2

#622 Deliverable 2
  1907-01-21.xml
  1907-01-22.xml
  1907-01-23.xml
Labels: deliverable2, deliverable3

#666 derivable 3
  1907-05-13.xml
Labels: complete, deliverable3

#684 1907-06-21.xml
  1907-06-21.xml
Labels: deliverable8

#679 1907-06-19.xml
  1907-06-19.xml
Labels: deliverable5

#680 1907-06-20.xml
  1907-06-20.xml
Labels: deliverable7

#671 1907-05-23
  1907-05-22.xml
  1907-05-23.xml
Labels: complete, deliverable5, deliverable7

#654 Deliverable 4
  1906-10-09.xml
  1906-10-10.xml
  1906-10-11.xml
Labels: deliverable4, deliverable5
